name: Entourage
dev_name: Entourage
mailjet_template:
  welcome: 311246
store_short_url: https://bit.ly/applientourage
links:
  feedback: https://entourage-asso.typeform.com/to/QeQ4X7?user_id=%{user_id}
  ethics-charter:             https://entourage-asso.typeform.com/to/EyAIut?user_id=%{user_id}
  ethics-charter-preprod:     https://entourage-asso.typeform.com/to/whN9kq?user_id=%{user_id}
  ethics-charter-pro:         https://entourage-asso.typeform.com/to/N4AqyO?user_id=%{user_id}
  ethics-charter-pro-preprod: https://entourage-asso.typeform.com/to/LI7viw?user_id=%{user_id}
roles:
  - ambassador
admin_roles:
  - moderator
group_types:
  action:
    message_types: [text, share]
    roles: [creator, member]
  conversation:
    message_types: [text, share]
    roles: [participant]
  outing:
    message_types: [text, share]
    roles: [organizer, participant]
  group:
    message_types: [text, share]
    roles: [admin, member]
targeting_profiles:
  - offers_help
  - asks_for_help
  - partner
  - ambassador
  - team
goals:
  - offer_help
  - ask_for_help
  - organization
